name 'joshuar-vnstat'
version '0.2.1'
source 'git://github.com/joshuar/puppet-vnstat'
author 'Joshua Rich'
license 'Apache Version 2.0'
summary 'vnstat module'
description "vnstat module for Debian and RedHat based Linux distributions."
project_page 'http://github.com/joshuar/puppet-vnstat'
dependency 'puppetlabs/stdlib', '>=0.1.6'
